### ISSUE TITLE
Unable to Uninstall Apps in Fun touch OS - Iqoo 12 

### ISSUE THREAD

**Issue by hrithwikbharadwaj** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#194]
**Describe the bug**
I am unable to uninstall the prebuilt apps like the browser with pm.

```java
Failure [DELETE_FAILED_USER_RESTRICTED]
```

Also trying to disable the app is giving me the below error

```java
java.lang.SecurityException: Cannot disable com.vivo.appstore no root permission
	at com.android.server.pm.PackageManagerService.setEnabledSettingInternalLocked(PackageManagerService.java:4566)
	at com.android.server.pm.PackageManagerService.setEnabledSettings(PackageManagerService.java:4470)
	at com.android.server.pm.PackageManagerService.-$$Nest$msetEnabledSettings(PackageManagerService.java:0)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.setApplicationEnabledSetting(PackageManagerService.java:6355)
	at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2523)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:292)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6986)
	at android.os.Binder.shellCommand(Binder.java:1134)
	at android.os.Binder.onTransact(Binder.java:954)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5024)
	at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6970)
	at android.os.Binder.execTransactInternal(Binder.java:1410)
	at android.os.Binder.execTransact(Binder.java:1341)

```

**Comment by AnonymousWP** [comment]
That's because system apps are on the system partition, which cannot be written by the user. In that case, try disabling.

**Comment by hrithwikbharadwaj** [comment]
No option to disable it in the phone nor in adb (not working)

**Comment by AnonymousWP** [comment]
There's an option in UAD-ng's settings. Check that.
