### ISSUE TITLE
Unable to Disable System Packages via ADB Using UAD-ng Despite Successful Uninstallation

### ISSUE THREAD

**Issue by LorandMarton** [Universal-Debloater-Alliance/universal-android-debloater-next-generation#666]
### Describe the bug

It appears that this is likely not a bug in UAD-ng (Universal Android Debloater Next Generation) itself but rather an issue related to ADB or Android system permissions. When attempting to disable certain system packages, such as com.qualcomm.location.

The following error is encountered:

```
Exception occurred while executing 'disable-user':
java.lang.SecurityException: Cannot disable system packages.
```

However, I am able to uninstall these packages using UAD-ng, suggesting that the issue may be with ADB's ability to disable system-level packages, likely due to system protections enforced by the OS.

Android OS: Xiaomi HyperOS
ADB Version: Latest

Does anyone have ideas or suggestions for a potential workaround for this issue?

When the popup appears with Failed to perform ADB operation, the log cannot be copied.

### Expected behavior

It should be possible to disable system packages.

### Operating System

Windows

### Provide logs

<details><summary>Log</summary>

```
adb shell pm disable-user --user 0 com.qualcomm.location

Exception occurred while executing 'disable-user':
java.lang.SecurityException: Cannot disable system packages.
        at com.android.server.pm.PackageManagerServiceImpl.canBeDisabled(PackageManagerServiceImpl.java:691)
        at com.android.server.pm.PackageManagerService.setEnabledSettings(PackageManagerService.java:4066)
        at com.android.server.pm.PackageManagerService.-$$Nest$msetEnabledSettings(Unknown Source:0)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.setApplicationEnabledSetting(PackageManagerService.java:5933)
        at com.android.server.pm.PackageManagerShellCommand.runSetEnabledSetting(PackageManagerShellCommand.java:2502)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:273)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(PackageManagerService.java:6573)
        at android.os.Binder.shellCommand(Binder.java:1075)
        at android.os.Binder.onTransact(Binder.java:895)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:4352)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(PackageManagerService.java:6557)
        at android.os.Binder.execTransactInternal(Binder.java:1351)
        at android.os.Binder.execTransact(Binder.java:1282)
```
</details>

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by AnonymousWP** [comment]
I appreciate you're reporting this, but as this is a question related to ADB and not an issue with UAD-ng, I will be converting this to a Discussion.
